### ISSUE TITLE
Calling getToken returns Error acquiring token: BrowserAuthError: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API. 

### ISSUE THREAD

**Issue by hahhen** [MazenSenih/MsalWithNextJs14#1]
I've been trying to fetch it on my own, but I had the same error. When using getToken from msal.js, it throws this error:

![image](https://github.com/MazenSenih/MsalWithNextJs14/assets/81843610/8bb57156-21f2-41e2-857a-ecf309493c25)

**Comment by hahhen** [comment]
Have you tested that function?

**Comment by MazenSenih** [comment]
Hi @hahhen ,
Yes it works for me, here are some notes to consider:

Call this function from a client component like this:
```
'use client'

import { getToken } from "@/msal/msal";
import { useEffect } from "react";

export default function AnyPage() {
    useEffect(() => {
        async function fetchToken() {
            await getToken().then(response => {
                alert(`token is ${response}`)
            });
        }
        fetchToken();
    })
    
    return (<>Your page components goes here</>)
}
```
Let me know if this worked for you.
